-- 1. 온라인 데이터 추출
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
       PRODUCT_ID, 
       USER_ID, 
       SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

UNION ALL

-- 2. 오프라인 데이터 추출 (USER_ID 자리에 NULL을 강제로 넣음)
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
       PRODUCT_ID, 
       NULL AS USER_ID, -- 오프라인은 유저ID가 없으므로 NULL 처리
       SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

-- 3. 합쳐진 전체 결과에 대해 정렬
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;