SELECT 
    A1.CAR_ID, 
    A1.CAR_TYPE, 
    FLOOR(A1.DAILY_FEE * 30 * (1 - A3.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A1
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN A3
    ON A1.CAR_TYPE = A3.CAR_TYPE 
    AND A3.DURATION_TYPE = '30일 이상'
WHERE 
    (A1.CAR_TYPE = '세단' OR A1.CAR_TYPE = 'SUV')
    AND A1.CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND FLOOR(A1.DAILY_FEE * 30 * (1 - A3.DISCOUNT_RATE / 100)) >= 500000 
    AND FLOOR(A1.DAILY_FEE * 30 * (1 - A3.DISCOUNT_RATE / 100)) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;