-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT D.ID, D.PARENT_ID, GENERATION + 1 
    FROM ECOLI_DATA D JOIN ECOLI_GEN G
    ON G.ID=D.PARENT_ID
)
SELECT COUNT(ID) AS COUNT, GENERATION
FROM ECOLI_GEN
WHERE  ID NOT IN (SELECT ID
FROM ECOLI_GEN
WHERE ID IN (SELECT PARENT_ID FROM ECOLI_GEN))
GROUP BY GENERATION
ORDER BY GENERATION