SELECT 
    SUB.HISTORY_ID,
    FLOOR(SUB.DAILY_FEE * SUB.DURATION * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM (
    -- 1. 대여 기록별로 기간과 해당되는 할인 타입을 먼저 계산하는 서브쿼리
    SELECT 
        H.HISTORY_ID,
        C.DAILY_FEE,
        C.CAR_TYPE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION,
        CASE 
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL 
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
) AS SUB
-- 2. 서브쿼리 결과와 할인 정책 테이블을 '트럭' 및 '기간 타입'으로 조인
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON SUB.CAR_TYPE = P.CAR_TYPE AND SUB.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, SUB.HISTORY_ID DESC;