SELECT FLAVOR
FROM (
    -- 상반기 데이터와 7월 데이터를 하나로 합칩니다.
    SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
    UNION ALL
    SELECT FLAVOR, TOTAL_ORDER FROM JULY
) AS COMBINED_ORDERS
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;