-- 코드를 입력하세요
WITH RECURSIVE DAYTIME AS(
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1 
    FROM DAYTIME
    WHERE HOUR <23
)

SELECT D.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM DAYTIME D LEFT JOIN ANIMAL_OUTS A
ON D.HOUR = HOUR(A.DATETIME)
GROUP BY D.HOUR
ORDER BY D.HOUR