-- 코드를 작성해주세요
SELECT B.ID, A.FISH_NAME, A.LENGTH
FROM 
(SELECT B.FISH_TYPE, B.FISH_NAME, MAX(A.LENGTH) AS LENGTH
FROM FISH_INFO A JOIN FISH_NAME_INFO B
 ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY B.FISH_NAME, B.FISH_TYPE) A JOIN FISH_INFO B
ON A.LENGTH = B.LENGTH AND A.FISH_TYPE = B.FISH_TYPE