SELECT S.TOTAL_SCORE AS SCORE, H.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES H JOIN 
(SELECT EMP_NO, SUM(SCORE) AS TOTAL_SCORE
FROM HR_GRADE
GROUP BY EMP_NO) S
ON H.EMP_NO = S.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;